### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by heaton1** [RedNax67/MMM-WunderGround#20]
Hello! 

I've got four copies of the module running, except they all have they same weather. Each have a different pws and apikey, and yet all report the same weather. 

Is there a way to run multiple instances of this module?

**Comment by RedNax67** [comment]
Unfortunately not. This is caused by the node_helper.js which handles the actual api requests. To keep from exhausting the api requests only one node_helper.js will be started. Other module instances will receive the exact same message sent by the node_helper and thus display the same information. 

Older versions did allow for multiple locations because the requests where handled by the browser, however they would periodically stop updating.

**Comment by RedNax67** [comment]
You could do it bu having multiple copies of the MMM-Winderground dir on your pi, naming them forinstance MMM-WunderGround1, 2, 3, etc.. Then you'd have to go in to the main js and modify the module name to reflect the dirname. Also you'd have to modify the ipc message name in both the main js and node_helper.js to make it unique to this instance of the module.  You'd also have to have multiple entries in the config.js reflecting the relevant modulename.

**Comment by heaton1** [comment]
Alright! Thank you for quickly clearing that up. I'll play around with it a bit and see if I can fandangle it to cooperate.
